//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:06:31 PM SAMT 
//


package com.example.students;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Abiturient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Abiturient">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/students}PersonType">
 *       &lt;sequence>
 *         &lt;element name="average-mark" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Abiturient", propOrder = {
    "averageMark"
})
public class Abiturient
    extends PersonType
{

    @XmlElement(name = "average-mark")
    protected double averageMark;

    /**
     * Gets the value of the averageMark property.
     * 
     */
    public double getAverageMark() {
        return averageMark;
    }

    /**
     * Sets the value of the averageMark property.
     * 
     */
    public void setAverageMark(double value) {
        this.averageMark = value;
    }

}
